# Generated by Django 2.1.2 on 2018-10-13 05:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市名称')),
                ('desc', models.CharField(max_length=200, verbose_name='城市描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='机构名称')),
                ('desc', models.TextField(verbose_name='机构名称')),
                ('hits', models.IntegerField(default=0, verbose_name='点击数')),
                ('nums_of_staring', models.IntegerField(default=0, verbose_name='收藏数')),
                ('image', models.ImageField(max_length=200, upload_to='organization/%Y/%m', verbose_name='机构封面')),
                ('address', models.CharField(max_length=200, verbose_name='机构地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CityDict', verbose_name='城市')),
            ],
            options={
                'verbose_name': '课程机构信息',
                'verbose_name_plural': '课程机构信息',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='教师姓名')),
                ('working_experience', models.IntegerField(default=0, verbose_name='工作经验')),
                ('company', models.CharField(max_length=50, verbose_name='公司')),
                ('position', models.CharField(max_length=50, verbose_name='职位')),
                ('features_of_teaching', models.CharField(max_length=50, verbose_name='教学特点')),
                ('hits', models.IntegerField(default=0, verbose_name='点击数')),
                ('nums_of_staring', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '机构教师信息',
                'verbose_name_plural': '机构教师信息',
            },
        ),
    ]
