# Generated by Django 2.1.2 on 2018-10-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20181017_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.IntegerField(choices=[(1, '培训机构'), (2, '高校'), (3, '个人')], default=2, verbose_name='机构类别'),
        ),
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(max_length=200, upload_to='organization/%Y/%m', verbose_name='Logo'),
        ),
    ]
