# Generated by Django 2.1.2 on 2018-10-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20181020_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
