# Generated by Django 2.1.2 on 2018-10-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181022_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='标签'),
        ),
    ]
