# Generated by Django 2.1.2 on 2018-10-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notice',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='课程公告'),
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='视频地址'),
        ),
    ]
