# Generated by Django 2.1.2 on 2018-10-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_image'),
        ('courses', '0007_teachernotice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachernotice',
            name='course',
        ),
        migrations.RemoveField(
            model_name='teachernotice',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='learn_what',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='具体内容'),
        ),
        migrations.AddField(
            model_name='course',
            name='need_know',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='讲师'),
        ),
        migrations.DeleteModel(
            name='TeacherNotice',
        ),
    ]
